# Generated by Django 5.1.6 on 2025-03-21 08:19

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dish_name', models.CharField(default='NULL', max_length=50, primary_key=True, serialize=False, validators=[owner.models.validate_dish_name])),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('dish_category', models.CharField(default='NULL', max_length=50)),
                ('dish_image', models.ImageField(default='image.png', upload_to='')),
                ('dish_sluger', models.SlugField(default='')),
                ('dish_veg', models.CharField(choices=[('Veg', 'Vegitarian'), ('Non Veg', 'Non Vegitarian')], default='Veg', max_length=10)),
                ('dish_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            managers=[
                ('test', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corderDate', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], max_length=50)),
                ('customerDish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.dishes')),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
