# Generated by Django 5.1.6 on 2025-03-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_veg',
            field=models.TextField(blank=True),
        ),
    ]
