# Generated by Django 5.1.6 on 2025-03-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_dishes_dish_detail_alter_dishes_dish_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customerDish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owner.dishes'),
        ),
    ]
