# Generated by Django 5.1.6 on 2025-03-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_orders_customerdish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customerDish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.dishes'),
        ),
    ]
