# Generated by Django 5.1.6 on 2025-03-28 06:15

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_orders_customerdish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[owner.models.validate_dish_name]),
        ),
    ]
